---


gnome_extension_target:
  - { id: '1401',  name: 'Bluetooth quick connect' }
  - { id: '906',  name: 'Sound Input & Output Device Chooser' }
  - { id: '3843',  name: 'custom hot corners extended' }
  - { id: '4167',  name: 'Just perfection desktop' }

gnome_enable_extensions:
  - 'pamac-updates@manjaro.org'
  - 'dash-to-dock@micxgx.gmail.com'
  - 'appindicatorsupport@rgcjonas.gmail.com'
  - 'gnome-ui-tune@itstime.tech'
  - 'x11gestures@joseexposito.github.io'
  - 'sound-output-device-chooser@kgshank.net'
  - 'bluetooth-quick-connect@bjarosze.gmail.com'
  - 'custom-hot-corners-extended@G-dH.github.com'
  - 'just-perfection-desktop@just-perfection'