- name: users | remove preinstalled clutter from home directory
  tags: dotfiles
  file:
    path: "/home/{{ username }}/{{ item }}"
    state: absent
  with_items:
    - examples.desktop

- name: users | create personal config directories
  tags: dotfiles
  file:
    path: /home/{{ username }}/{{ item.dir }}
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - { dir: Desktop }
    - { dir: Documents }
    - { dir: Downloads }
    - { dir: Projects }
    - { dir: Templates }
    - { dir: dev }
    - { dir: blog }
    - { dir: pro }
    - { dir: docs }
    - { dir: pi }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: /usr/local/etc/my.cnf.d }

# - name: users | copy profile image
#   tags: dotfiles
#   copy:
#     src: users/{{ username }}/profile_image.png
#     dest: /var/lib/AccountsService/icons/{{ username }}.png
#     owner: root
#     group: root
#     mode: 0644