# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/tg.yml

  ## desktop environments
  - include_tasks: desktop_environments/mate/appearance.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/caja.yml
    when: mate is defined and mate == true

  # - include_tasks: desktop_environments/mate/keybindings.yml
  #   when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/packages.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/peripherals.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/terminal.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/workspace_settings.yml
    when: mate is defined and mate == true

  # - include_tasks: desktop_environments/gnome/meta.yml
  #   when: gnome is defined and gnome == true
  - include_tasks: desktop_environments/gnome/appearance.yml
    when: gnome is defined and gnome == true

  # - include_tasks: desktop_environments/gnome/keybindings.yml
  #   when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/nautilus.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/packages.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/peripherals.yml
    when: gnome is defined and gnome == true

  # - include_tasks: desktop_environments/gnome/shell_settings.yml
  #   when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/terminal.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/tracker.yml
    when: gnome is defined and gnome == true

  ## system setup
  # - import_tasks: system_setup/autofs.yml
  # - import_tasks: system_setup/scripts.yml
  # - import_tasks: system_setup/tweaks.yml

  ## install software
  - import_tasks: software/packages_pacman.yml

  rescue:
    - set_fact: task_failed=true
