- name: users | tg | create group
  tags: groups,tg,users
  become_user: "tg"
  group:
    name: wheel
    state: present

- name: users | tg | create user
  tags: tg,sudo,users
  # ansible.builtin.debug:
  #   var: mypassword
  vars:
    mypassword: "{{ lookup('community.general.passwordstore', 'ansible/workstation/tg missing=create length=32 nosymbols=true')}}"
  user:
    name: tg
    group: tg
    groups: wheel,users,{{ sudo_group }}
    state: present
    comment: "Thomas Groch"
    password: "{{ tg_passwd | mypassword }}"
    shell: /usr/bin/zsh
    # shell: /usr/bin/nologin

- name: users | tg | add sudoers file
  tags: settings,tg,sudo,system,users
  copy:
    src: users/sudoers_tg
    dest: /etc/sudoers.d/tg
    owner: root
    group: root
    mode: 0440

- name: users | tg | create .ssh directory
  tags: dotfiles,tg,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: tg
    group: tg
    mode: 0700
  with_items:
    - { dir: '/home/tg/.ssh' }

- name: users | tg | add public key
  tags: dotfiles,tg,ssh,ssh-keys,users
  authorized_key:
    user: tg
    key: "{{ item }}"
  with_file:
    - users/tg/ssh/tgroch_id_rsa.pub
    # - users/tg/ssh/tg_id_ed25519.pub

# ensure git repositories
- name: Git | Checkout git bare repository
  become_user: "tg"
  git:
    repo: "{{ upstream }}"
    dest: "{{ repo_dir }}"
    bare: yes
    update: no
    track_submodules: yes
  tags: dotfiles,tg,users,barerepo

- name: Git | Ensure repository set properly
  lineinfile: dest={{ repo_dir }}/config
              regexp="^\s*bare.?="
              line="    bare = false"
  tags: dotfiles,tg,users,barerepo

- name: Git | Ensure proper worktree
  lineinfile: dest={{ repo_dir }}/config
              regexp='^\s*worktree.?='
              line="    worktree = {{ work_dir }}"
  tags: dotfiles,tg,users,barerepo

- name: Git | Ensure work dir
  file: path={{ work_dir }} state=directory
        mode=0775
  tags: dotfiles,tg,users,barerepo


# fetch/checkout
- name: Git | Fetching new changes
  shell: chdir={{ repo_dir }} git fetch --prune && git fetch --tags
  become_user: "tg"
  tags: dotfiles,tg,users,barerepo

- name: Git | Checkout version
  command: "chdir={{ work_dir }} git --git-dir={{ repo_dir }} checkout -f {{ version | default('HEAD') }}"
  become_user: "tg"
  tags: dotfiles,tg,users,barerepo

# - name: Git | Checkout dotfiles updates
#   command: "chdir={{ work_dir }} git fetch && git checkout master && git merge upstream/master"
#   become_user: "tg"
#   tags: dotfiles,tg,users,barerepo

# git submodules
- name: Git | Submodules | Syncing
  command: chdir={{ work_dir }} git --git-dir={{ repo_dir }} submodule sync
  become_user: "tg"
  tags: dotfiles,tg,users,barerepo,update

- name: Git | Submodules | Updating
  command: chdir={{ work_dir }} git --git-dir={{ repo_dir }} submodule update -f --init --recursive
  become_user: "tg"
  tags: dotfiles,tg,users,barerepo,update

- name: Git | Ensure untracked files are hidden
  command: chdir={{ work_dir }} git --git-dir={{ repo_dir }} config --local status.showUntrackedFiles no
  become_user: "tg"
  tags: dotfiles,tg,users,barerepo,update

- name: Git | Create symbolic link
  file:
    src: "{{ repo_dir }}"
    dest: "{{ work_dir }}.git"
    owner: tg
    group: tg
    state: link
  become_user: "tg"
  tags: dotfiles,tg,users,barerepo