- name: gnome | appearance | copy lock screen and wallpaper background files
  tags: gnome,gnome-lockscreen
  with_items:
    - { src: files/gnome/wallpaper.png, dest: "/usr/share/backgrounds/default-wallpaper.png" }
    - { src: files/gnome/lockscreen.png, dest: "/usr/share/backgrounds/default-lockscreen.png" }
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "tg"
    group: wheel
    mode: 0644

- name: gnome | appearance | 
  tags: gnome,
  become_user: "tg"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/screensaver/picture-uri", value: "'file:///usr/share/backgrounds/default-lockscreen.png'" }
    - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:///usr/share/backgrounds/default-wallpaper.png'" }
    - { key: "/org/gnome/desktop/background/picture-options", value: "'zoom'" }