# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: debug
  become_user: "{{ username }}"
  vars:
    mypassword: "{{ lookup('community.general.passwordstore', 'ansible/workstation/tg missing=empty length=32 nosymbols=true') | default('123456', true) }}"
  debug: 
    var: mypassword

- name: debug2
  become_user: "{{ username }}"
  vars:
    mypassword: "{{ lookup('community.general.passwordstore', 'ansible/workstation/tg missing=empty length=32 nosymbols=true') | default('123456', true) }}"
  debug: 
    var: mypassword

- name: debug
  become_user: "{{ username }}"
  debug: msg="{{ lookup('community.general.passwordstore', 'ansible/workstation/tg missing=empty') | default('', true) }}"

- name: Ensure password is not empty and vault can be decrypted
  become_user: "{{ username }}"
  set_fact:
    mypassword: "{{ lookup('community.general.passwordstore', 'ansible/workstation/tg missing=empty') | default('', true) }}"

- block:

  # Make sure users exist on the system
  - import_tasks: users/root.yml
  - import_tasks: users/velociraptor.yml
  - import_tasks: users/tg.yml

  # Set up the ansible environment
  - import_tasks: ansible_setup.yml

  # install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_development.yml
  # - import_tasks: software/packages_cleanup.yml
  # - import_tasks: software/packages_pip.yml
  # - import_tasks: software/packages_utilities.yml

  # Perform remaining tasks:
  - import_tasks: system_setup/clock.yml
  - import_tasks: system_setup/cron.yml
  - import_tasks: system_setup/locale.yml
  - import_tasks: system_setup/logging.yml
  - import_tasks: system_setup/memory.yml
  - import_tasks: system_setup/microcode.yml
  - import_tasks: system_setup/openssh.yml
  # - import_tasks: system_setup/scripts.yml

  rescue:
    - set_fact: task_failed=true

  when: mypassword is defined and mypassword != ''

# otherwise output a message
- block:

  - fail: msg="Missing vault password"
  
  when: mypassword is not defined and mypassword == ''