- name: notify healthchecks.io that the job ran
  uri:
    url: https://hc-ping.com/{{ healthcheck_uuid }}
  changed_when: False
  when: healthcheck_uuid is defined

- name: Temp clone git project to get commit id
  git:
    repo: "{{ upstream }}"
    clone: no
  register: result_git

- name: send completion notification via telegram
  tags: always,telegram
  telegram:
    token: "{{ telegram_token }}"
    api_args:
      chat_id: "{{ telegram_chat_id }}"
      parse_mode: "markdown"
      text: "👍 *{{ ansible_hostname }}* provision finished. *{{ result_git.after }}* is last commit revision of the repository retrieved during the update."
  changed_when: False
