name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    # runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it- uses: actions/c
    - uses: actions/checkout@master
    - name: Run bootstrap
      shell: bash
      run: |
        ./bootstrap.sh  
      env:
        REPO: ${{github.workspace}}
        DOTFILES_REF: ${{github.sha}}
