name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    # runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it- uses: actions/c
    - uses: actions/checkout@master
    # - name: Configure GPG Key
    #   run: |
    #     echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
    #   env:
    #     GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    - name: Run bootstrap
      shell: bash
      run: |
        ./bootstrap.sh "https://github.com/thomasgroch/password-store-for-testing.git" "runner"
      env:
        WORKSPACE_PATH: ${{github.workspace}}
        DOTFILES_REF: ${{github.sha}}
