name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    # runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it- uses: actions/c
    - uses: actions/checkout@master
    # - 
    #   name: Configure GPG Key
    #   run: |
    #     echo -n "${GPG_SIGNING_KEY}" | base64 --decode | gpg --import
    #   env:
    #     GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        fingerprint: "430A44F67F9547FD18B0C0A10D7B0F5C2D5E1888"
    -
      name: List keys
      run: gpg -K
    - 
      name: Run bootstrap
      shell: bash
      # ./bootstrap.sh "https://github.com/thomasgroch/password-store-for-testing.git" "tg"
      run: |
        git clone "https://github.com/thomasgroch/password-store-for-testing.git" ~/.password-store
        sudo apt install -y pass
        pass show "ansible/workstation/runner"
      env:
        WORKSPACE_PATH: ${{github.workspace}} # "/home/runner/work/dotfiles/dotfiles"
        DOTFILES_REF: ${{github.sha}} # "8acd4815dfe44ee26810b01e6a0129f13781480a"